### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by MrChangyaohua** [bingoogolapple/BGASwipeItemLayout-Android#2]
E/InputEventReceiver(23376): Exception dispatching input event.
F/MobUncaughtExceptionHandler(23376): length=2; index=-1
F/MobUncaughtExceptionHandler(23376): java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
F/MobUncaughtExceptionHandler(23376):   at android.support.v4.widget.ViewDragHelper.processTouchEvent(ViewDragHelper.java:1147)
F/MobUncaughtExceptionHandler(23376):   at cn.bingoogolapple.swipeitemlayout.BGASwipeItemLayout.onTouchEvent(BGASwipeItemLayout.java:328)
F/MobUncaughtExceptionHandler(23376):   at android.view.View.dispatchTouchEvent(View.java:7719)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
F/MobUncaughtExceptionHandler(23376):   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2077)
F/MobUncaughtExceptionHandler(23376):   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1522)
F/MobUncaughtExceptionHandler(23376):   at android.app.Activity.dispatchTouchEvent(Activity.java:2587)
F/MobUncaughtExceptionHandler(23376):   at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
F/MobUncaughtExceptionHandler(23376):   at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
F/MobUncaughtExceptionHandler(23376):   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2025)
F/MobUncaughtExceptionHandler(23376):   at android.view.View.dispatchPointerEvent(View.java:7899)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3997)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3874)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3485)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3454)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3561)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3462)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3618)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3485)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3454)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3462)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5582)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5562)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5533)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5665)
F/MobUncaughtExceptionHandler(23376):   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
F/MobUncaughtExceptionHandler(23376):   at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
F/MobUncaughtExceptionHandler(23376):   at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5638)
F/MobUncaughtExceptionHandler(23376):   at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5684)
F/MobUncaughtExceptionHandler(23376):   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
F/MobUncaughtExceptionHandler(23376):   at android.view.Choreographer.doCallbacks(Choreographer.java:574)
F/MobUncaughtExceptionHandler(23376):   at android.view.Choreographer.doFrame(Choreographer.java:

@Override
    public boolean onTouchEvent(MotionEvent event) {
        mDragHelper.processTouchEvent(event);         //此处为328错误的出处
        mGestureDetectorCompat.onTouchEvent(event);
        return true;
    }

**Comment by MrChangyaohua** [comment]
不是BUG，忘记加以下的一句话，Sorry！
recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                if (RecyclerView.SCROLL_STATE_DRAGGING == newState) {
                    bankCardDeleteAdapter.closeOpenedSwipeItemLayoutWithAnim();
                }
            }
        });
