### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by MrChangyaohua** [bingoogolapple/BGASwipeItemLayout-Android#3]
为什么会出现以下的问题呢？我的那里用法不对吗？

02-24 19:19:50.583 24573-24573/? E/InputEventReceiver: Exception dispatching input event.
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler: length=2; index=-1
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler: java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.support.v4.widget.ViewDragHelper.processTouchEvent(ViewDragHelper.java:1147)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at cn.bingoogolapple.swipeitemlayout.BGASwipeItemLayout.onTouchEvent(BGASwipeItemLayout.java:328)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.View.dispatchTouchEvent(View.java:7719)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2238)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2077)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1522)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.app.Activity.dispatchTouchEvent(Activity.java:2587)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2025)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.View.dispatchPointerEvent(View.java:7899)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3997)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3874)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3485)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3454)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3561)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3462)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3618)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3485)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3454)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3462)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5582)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5562)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5533)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5665)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5638)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5684)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.Choreographer.doCallbacks(Choreographer.java:574)
02-24 19:19:50.603 24573-24573/? A/MobUncaughtExceptionHandler:     at android.view.Choreographer.doFrame(Choreographer.java:

**Comment by MrChangyaohua** [comment]
当我大量重复测试此控件时就会出现以上的错误崩溃，求大神指点。
